#!/usr/bin/env python3
"""Resolve an explicit role policy; never silently switch provider or model."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def resolve(provider, role, risk='high', *, candidate=False, principal=None, available=None, policy=None):
    policy = policy or json.loads((ROOT / 'workflows/model-policy.json').read_text())
    if provider not in policy['principal'] or role not in policy['roles']:
        raise ValueError('Fournisseur ou rôle inconnu')
    if risk not in ('normal', 'high'):
        raise ValueError('Risque inconnu : conserver le principal')
    rule = policy['roles'][role]
    base = principal or policy['principal'][provider]
    result = {'provider': provider, 'role': role, 'risk': risk, 'requested_model': base,
              'requested_effort': None, 'observed_model': None, 'observed_effort': None,
              'policy': 'principal', 'availability': 'unverified'}
    if candidate:
        if role == 'orchestrator' or risk not in rule['allowed_risk'] or not rule['candidate']:
            raise ValueError('Ce rôle/risque exige le modèle principal')
        config = rule['candidate'][provider]
        result.update(requested_model=config['model'], requested_effort=config['effort'], policy=rule['status'])
    if available is not None:
        result['availability'] = 'available' if result['requested_model'] in available else 'unavailable'
    return result


def codex_agent(name, description, body):
    # TOML basic strings accept JSON escapes; non-ASCII remains literal.
    return '# Generated by odoo19-agents/build.sh; edit canonical roles only.\n' + '\n'.join(f'{key} = {json.dumps(value, ensure_ascii=False)}' for key, value in {
        'name': name, 'description': description, 'developer_instructions': body,
    }.items()) + '\n'


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('provider', choices=['codex', 'claude'])
    parser.add_argument('role')
    parser.add_argument('--risk', choices=['normal', 'high'], default='high')
    parser.add_argument('--candidate', action='store_true', help='Choix expérimental explicite pour tâche bornée')
    parser.add_argument('--principal', help='Modèle principal effectif de la session, conservé')
    parser.add_argument('--available', nargs='*', help='Identifiants annoncés par le fournisseur ; absent = non vérifié')
    args = parser.parse_args()
    try:
        print(json.dumps(resolve(args.provider, args.role, args.risk, candidate=args.candidate,
                                 principal=args.principal, available=args.available), ensure_ascii=False, indent=2))
    except ValueError as exc:
        parser.exit(2, str(exc) + '\n')
